name: einstein
description: A platform for exchanging ideas.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  hive: ^2.0.6
  crypto: ^3.0.1
  file_picker: ^4.5.1
  intl: ^0.17.0

  flutterfire_cli: ^0.2.1+1
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  firebase_database: ^9.0.10
  firebase_storage: ^10.2.15

  flutter_swipable: ^1.2.1
  comment_box: ^0.0.17
  flutter_login: ^3.2.0
  login_screen: ^0.6.0
  flutter_typeahead: ^3.2.5
  connectivity_plus: ^2.3.0
  overlay_support: ^1.2.1
  connectivity: ^3.0.6
  flutter_settings_screens: ^0.3.2-null-safety
  google_fonts: ^2.3.2
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
