name: Flutter CI

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - main
    - codecov
   
jobs:
  aspell: # REAME.md Spell Checker
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: rojopolis/spellcheck-github-actions@0.27.0
        name: Spellcheck
        with:
          config_path: .spellcheck.yml 
          source_files: README.md CHANGELOG.md notes/Notes.md
          task_name: Markdown
          output_file: spellcheck-output.txt

      # Upload spell check report as a GitHub Artifact
      - uses: actions/upload-artifact@v3
        with:
          name: Spellcheck Report
          path: spellcheck-output.txt

  code_metric: # Check Code Metric
    name: Dart Code Metric
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dart-code-metrics
        uses: dart-code-checker/dart-code-metrics-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  

  build_web: # Build for Android and Web
    name: Web Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: "zulu"
          java-version: "12"
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.1'
          channel: 'stable'
      - name: Get Dependencies
        run: flutter pub get
      - name: Build
        run: flutter build web

  build_android: # Build for Android and Web
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@latest
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.0.2
      - name: Install dependancies
        run: flutter pub get
      - name: Run Lint
        run: flutter analyze .
      - name: Build APK
        run: flutter build apk 
      - name: Upload APK Artifact    # Upload generated apk to the artifacts.
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk